### ISSUE TITLE
Feature: add namespace to tenant namespaces

### ISSUE THREAD

**Issue by ppodevlabs** [projectcapsule/capsule-addon-fluxcd#3]
## Background
With the actual setup, the initial namespace created for the tenant is not part of the tenant
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: oil-system
```

Causing the tenant owners not being able to list this namespace and manage resources within that namespace. In the flux example, tenant owners wont be able to handle the kustomization/gitrepository which is the root of their workloads.

## Proposal
Make the flux addon capable of modifying the owners reference of the namespace based in a label/annotation, ie: `capsule.clastix.io/tenant: oil`. Making this namespace part of the tenant so tenant owners can work with it.

**Comment by maxgio92** [comment]
Hi @ppodevlabs, sorry for the delay.

I like the idea and I agree. I'll work on this and keep you posted! 😃

**Comment by ppodevlabs** [comment]
looking forward to have this feature
